services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: seo-tool-backend:latest
    container_name: seo-tool-container
    ports:
      - "6969:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/sql_app.db:/app/backend/sql_app.db
